/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abhijeek' at '2/20/17 6:25 PM' with Gradle 3.0
 *
 * @author abhijeek, @date 2/20/17 6:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
